# Generated by Django 5.0.3 on 2024-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0002_rename_plantas_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
